// This script was made by choombdev for Odyssey 3, reusing it without explicit permission is not allowed.
onEvent('recipes', event => {
   // Replacing all empty tag with actual ingredients.
event.replaceInput({}, '#forge:leafyvegetables', ['pamhc2crops:scallionitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
event.replaceInput({}, '#forge:salad_ingredients', ['pamhc2crops:scallionitem', 'pamhc2crops:turnipitem', 'pamhc2crops:tomatoitem', 'pamhc2crops:cucumberitem', 'pamhc2crops:lettuceitem', 'pamhc2crops:bellpepperitem', 'pamhc2crops:onionitem', 'pamhc2crops:chilipepperitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:cornitem', 'pamhc2crops:broccoliitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:eggplantitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
event.replaceInput({}, '#forge:vegetables', ['pamhc2crops:scallionitem', 'pamhc2crops:turnipitem', 'pamhc2crops:tomatoitem', 'pamhc2crops:cucumberitem', 'pamhc2crops:lettuceitem', 'pamhc2crops:bellpepperitem', 'pamhc2crops:onionitem', 'pamhc2crops:chilipepperitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:cornitem', 'pamhc2crops:broccoliitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:eggplantitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
})

onEvent('tags.items', event => {
   event.add('forge:vegetables', ['pamhc2crops:scallionitem', 'pamhc2crops:turnipitem', 'pamhc2crops:tomatoitem', 'pamhc2crops:cucumberitem', 'pamhc2crops:lettuceitem', 'pamhc2crops:bellpepperitem', 'pamhc2crops:onionitem', 'pamhc2crops:chilipepperitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:cornitem', 'pamhc2crops:broccoliitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:eggplantitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
   event.add('forge:leafyvegetables', ['pamhc2crops:scallionitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
   event.add('forge:salad_ingredients', ['pamhc2crops:scallionitem', 'pamhc2crops:turnipitem', 'pamhc2crops:tomatoitem', 'pamhc2crops:cucumberitem', 'pamhc2crops:lettuceitem', 'pamhc2crops:bellpepperitem', 'pamhc2crops:onionitem', 'pamhc2crops:chilipepperitem', 'pamhc2crops:artichokeitem', 'pamhc2crops:chickpeaitem', 'pamhc2crops:asparagusitem', 'pamhc2crops:cornitem', 'pamhc2crops:broccoliitem', 'pamhc2crops:caulifloweritem', 'pamhc2crops:cabbageitem', 'pamhc2crops:celeryitem', 'pamhc2crops:eggplantitem', 'pamhc2crops:spinachitem', 'pamhc2crops:rhubarbitem'])
})