
#Common configuration settings
[common]

	#Crafting Settings.
	[common.crafting]
		#Whether Fluid Traders can be crafted.
		#Also affects crafting of fluid trader accessories (Fluid Trader Interface, Fluid Capacity Upgrades, etc.)
		#Disabling will not remove any existing Fluid Traders from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowFluidTraderCrafting = true
		#Whether Fluid Tanks can be crafted.
		#Disabling will not remove any existing fluid tanks from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowFluidTankCrafting = true
		#Whether Energy Traders can be crafted.
		#Also affects crafting of energy trader accessories (Energy Trader Interface, Energy Capacity Upgrades, etc.)
		#Disabling will not remove any existing Energy Traders from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowEnergyTraderCrafting = true
		#Whether Batteries can be crafted.
		#Disabling will not remove any existing Batteries from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowBatteryCrafting = true

